import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Items",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/DI-35-removebg-preview.png",
    productName: "Sonalika DI-35",
    price: "35,000.00",
    color: "Green",
    badge: true,
    des: "A reliable tractor for all your farming needs.",
  },
  {
    _id: "202",
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_tractor_mf5710.png",
    productName: "Massey Ferguson 5710",
    price: "50,000.00",
    color: "Red",
    badge: true,
    des: "Powerful and efficient for large farms.",
  },
  {
    _id: "203",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar.jpg",
    productName: "Kubota Harvester",
    price: "45,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: "204",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Case_IH_JX90.png",
    productName: "Case IH JX90",
    price: "55,000.00",
    color: "Red",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: "205",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6095B-removebg-preview.png",
    productName: "John Deere 6095B",
    price: "60,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "206",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/DI-75-removebg-preview.png",
    productName: "Sonalika DI-75",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: "207",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6XXXB_OOS.png",
    productName: "John Deere 6XXXB OOS",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Robust and reliable for all farming needs.",
  },
  {
    _id: "208",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/MB-removebg-preview.png",
    productName: "McCormick MB85",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: "209",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/MB75-removebg-preview.png",
    productName: "McCormick MB75",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Compact and versatile for small farms.",
  },
  {
    _id: "210",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/TS6-125.png",
    productName: "New Holland TS6.125",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: "211",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/t6090-removebg-preview.png",
    productName: "New Holland T6090",
    price: "85,000.00",
    color: "Blue",
    badge: true,
    des: "High performance and efficiency.",
  },
  {
    _id: "212",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/375A-removebg-preview.png",
    productName: "Yanmar YM357A",
    price: "55,000.00",
    color: "Yellow",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "213",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/yanm-removebg-preview.png",
    productName: "Yanmar EF494T",
    price: "50,000.00",
    color: "Yellow",
    badge: true,
    des: "Ideal for small to medium farms.",
  },
  {
    _id: "214",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_TRACTOR_IMAGE-removebg-preview.png",
    productName: "JD 5095",
    price: "65,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: "215",
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_240.png",
    productName: "Massey Ferguson 240",
    price: "40,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "216",
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_400xtra.png",
    productName: "Massey Ferguson 400 Xtra",
    price: "55,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: "217",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Valtra_BL88.png",
    productName: "Valtra BL88",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for all farming needs.",
  },
  {
    _id: "218",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/NH_Combine_TC45.png",
    productName: "NH (Combine) TC4/5",
    price: "90,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: "219",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_9200.png",
    productName: "Mahindra 9200",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Powerful and efficient for large farms.",
  },
  {
    _id: "220",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Farmtrac_6060_Heritage.png",
    productName: "Farmtrac 6060 Heritage",
    price: "65,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: "221",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_TT75.png",
    productName: "New Holland TT75",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: "222",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_L3540.png",
    productName: "Kubota L3540",
    price: "70,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "223",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar_YT359.png",
    productName: "Yanmar YT359",
    price: "75,000.00",
    color: "Yellow",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "224",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mack_Granite_LR.png",
    productName: "Mack Granite LR",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: "225",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_420.png",
    productName: "Massey Ferguson 420",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: "226",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Ford_3910.png",
    productName: "Ford 3910",
    price: "50,000.00",
    color: "Blue",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "227",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Case_IH_JXT95.png",
    productName: "Case IH JXT95",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: "228",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF188.png",
    productName: "Massey Ferguson MF188",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "229",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF290.png",
    productName: "Massey Ferguson MF290",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Ideal for small to medium farms.",
  },
  {
    _id: "230",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Zetor_Proxima_CL100.png",
    productName: "Zetor Proxima CL100",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: "231",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Same_Laser_130.png",
    productName: "Same Laser 130",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "232",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/McCormick_T110_Max.png",
    productName: "McCormick T110 Max",
    price: "80,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: "233",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF165.png",
    productName: "Massey Ferguson MF165",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "234",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_TD80D.png",
    productName: "New Holland TD80D",
    price: "85,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: "235",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Ford_4610.png",
    productName: "Ford 4610",
    price: "50,000.00",
    color: "Blue",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "236",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/McCormick_D125.png",
    productName: "McCormick D125",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: "237",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Same_Tiger_80.4E.png",
    productName: "Same Tiger 80.4E",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "238",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_5630.png",
    productName: "New Holland 5630",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "239",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_7056.png",
    productName: "New Holland 7056",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "240",
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_volvo_fl7.png",
    productName: "Volvo FL-7",
    price: "100,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: "241",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_M7040.png",
    productName: "Kubota M7040",
    price: "85,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "242",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar.jpg",
    productName: "Yanmar Harvester",
    price: "50,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: "243",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_585_DI.png",
    productName: "Mahindra 585DI",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "244",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_480_HISTORY.png",
    productName: "Massey Ferguson 480",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "245",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/4-wd-5075-e-john-deere.png",
    productName: "JD 5075(2022)",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: "246",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6100D.png",
    productName: "JD 6100D",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "247",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/955_Harvester.png",
    productName: "955 Harvester",
    price: "90,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: "248",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/logo_large-1.png",
    productName: "Hello Tractor Demo Model",
    price: "0.00",
    color: "N/A",
    badge: true,
    des: "Demo model for showcasing features.",
  },
  {
    _id: "249",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/john_deere_5090e.png",
    productName: "John Deere 5090E",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "250",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6135B-removebg-preview.png",
    productName: "John Deere 6135B",
    price: "85,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "251",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/460_xtra-removebg-preview.png",
    productName: "Xtra 460",
    price: "90,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: "252",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6110_D.png",
    productName: "JD 6110 D",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "253",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/joohn_deere-removebg-preview.png",
    productName: "6170",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "254",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/jx_80-removebg-preview.png",
    productName: "jx 80",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "255",
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_tractor_mf7614.png",
    productName: "Massey Ferguson 7614",
    price: "90,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: "256",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6713-removebg-preview.png",
    productName: "6713",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "257",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/136_Preet_7549.png",
    productName: "Preet 7549 2WD",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: "258",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_6005.png",
    productName: "Mahindra 6005",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: "259",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_7618.png",
    productName: "Massey Ferguson 7618",
    price: "90,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "260",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/13_Sonalika_Di_750_III.png",
    productName: "Sonalika Di 750 III",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: "261",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Isuzu_FRR.png",
    productName: "Isuzu FRR",
    price: "100,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: "262",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_L4508.png",
    productName: "Kubota L4508",
    price: "85,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: "263",
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Isuzu_ELF_Tipper.png",
    productName: "Isuzu ELF Tipper",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============
export const paginationItems = [
  {
    _id: 1001,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/DI-35-removebg-preview.png",
    productName: "Sonalika DI-35",
    price: "35,000.00",
    color: "Green",
    badge: true,
    des: "A reliable tractor for all your farming needs.",
  },
  {
    _id: 1002,
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_tractor_mf5710.png",
    productName: "Massey Ferguson 5710",
    price: "50,000.00",
    color: "Red",
    badge: true,
    des: "Powerful and efficient for large farms.",
  },
  {
    _id: 1003,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar.jpg",
    productName: "Kubota Harvester",
    price: "45,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: 1004,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Case_IH_JX90.png",
    productName: "Case IH JX90",
    price: "55,000.00",
    color: "Red",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: 1005,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6095B-removebg-preview.png",
    productName: "John Deere 6095B",
    price: "60,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1006,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/DI-75-removebg-preview.png",
    productName: "Sonalika DI-75",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: 1007,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6XXXB_OOS.png",
    productName: "John Deere 6XXXB OOS",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Robust and reliable for all farming needs.",
  },
  {
    _id: 1008,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/MB-removebg-preview.png",
    productName: "McCormick MB85",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: 1009,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/MB75-removebg-preview.png",
    productName: "McCormick MB75",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Compact and versatile for small farms.",
  },
  {
    _id: 1010,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/TS6-125.png",
    productName: "New Holland TS6.125",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: 1011,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/t6090-removebg-preview.png",
    productName: "New Holland T6090",
    price: "85,000.00",
    color: "Blue",
    badge: true,
    des: "High performance and efficiency.",
  },
  {
    _id: 1012,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/375A-removebg-preview.png",
    productName: "Yanmar YM357A",
    price: "55,000.00",
    color: "Yellow",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1013,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/yanm-removebg-preview.png",
    productName: "Yanmar EF494T",
    price: "50,000.00",
    color: "Yellow",
    badge: true,
    des: "Ideal for small to medium farms.",
  },
  {
    _id: 1014,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_TRACTOR_IMAGE-removebg-preview.png",
    productName: "JD 5095",
    price: "65,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: 1015,
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_240.png",
    productName: "Massey Ferguson 240",
    price: "40,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1016,
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_400xtra.png",
    productName: "Massey Ferguson 400 Xtra",
    price: "55,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: 1017,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Valtra_BL88.png",
    productName: "Valtra BL88",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for all farming needs.",
  },
  {
    _id: 1018,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/NH_Combine_TC45.png",
    productName: "NH (Combine) TC4/5",
    price: "90,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: 1019,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_9200.png",
    productName: "Mahindra 9200",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Powerful and efficient for large farms.",
  },
  {
    _id: 1020,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Farmtrac_6060_Heritage.png",
    productName: "Farmtrac 6060 Heritage",
    price: "65,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: 1021,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_TT75.png",
    productName: "New Holland TT75",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: 1022,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_L3540.png",
    productName: "Kubota L3540",
    price: "70,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1023,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar_YT359.png",
    productName: "Yanmar YT359",
    price: "75,000.00",
    color: "Yellow",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1024,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mack_Granite_LR.png",
    productName: "Mack Granite LR",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: 1025,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_420.png",
    productName: "Massey Ferguson 420",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: 1026,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Ford_3910.png",
    productName: "Ford 3910",
    price: "50,000.00",
    color: "Blue",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1027,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Case_IH_JXT95.png",
    productName: "Case IH JXT95",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: 1028,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF188.png",
    productName: "Massey Ferguson MF188",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1029,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF290.png",
    productName: "Massey Ferguson MF290",
    price: "65,000.00",
    color: "Red",
    badge: true,
    des: "Ideal for small to medium farms.",
  },
  {
    _id: 1030,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Zetor_Proxima_CL100.png",
    productName: "Zetor Proxima CL100",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: 1031,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Same_Laser_130.png",
    productName: "Same Laser 130",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1032,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/McCormick_T110_Max.png",
    productName: "McCormick T110 Max",
    price: "80,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: 1033,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_MF165.png",
    productName: "Massey Ferguson MF165",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1034,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_TD80D.png",
    productName: "New Holland TD80D",
    price: "85,000.00",
    color: "Blue",
    badge: true,
    des: "Perfect for all types of farming tasks.",
  },
  {
    _id: 1035,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Ford_4610.png",
    productName: "Ford 4610",
    price: "50,000.00",
    color: "Blue",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1036,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/McCormick_D125.png",
    productName: "McCormick D125",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "Efficient and powerful for various applications.",
  },
  {
    _id: 1037,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Same_Tiger_80.4E.png",
    productName: "Same Tiger 80.4E",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1038,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_5630.png",
    productName: "New Holland 5630",
    price: "80,000.00",
    color: "Blue",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1039,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/New_Holland_7056.png",
    productName: "New Holland 7056",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1040,
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_volvo_fl7.png",
    productName: "Volvo FL-7",
    price: "100,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: 1041,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_M7040.png",
    productName: "Kubota M7040",
    price: "85,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1042,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Yanmar.jpg",
    productName: "Yanmar Harvester",
    price: "50,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: 1043,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_585_DI.png",
    productName: "Mahindra 585DI",
    price: "60,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1044,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_480_HISTORY.png",
    productName: "Massey Ferguson 480",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1045,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/4-wd-5075-e-john-deere.png",
    productName: "JD 5075(2022)",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and powerful for all applications.",
  },
  {
    _id: 1046,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6100D.png",
    productName: "JD 6100D",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1047,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/955_Harvester.png",
    productName: "955 Harvester",
    price: "90,000.00",
    color: "Yellow",
    badge: true,
    des: "Perfect for harvesting crops efficiently.",
  },
  {
    _id: 1048,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/logo_large-1.png",
    productName: "Hello Tractor Demo Model",
    price: "0.00",
    color: "N/A",
    badge: true,
    des: "Demo model for showcasing features.",
  },
  {
    _id: 1049,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/john_deere_5090e.png",
    productName: "John Deere 5090E",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1050,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6135B-removebg-preview.png",
    productName: "John Deere 6135B",
    price: "85,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1051,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/460_xtra-removebg-preview.png",
    productName: "Xtra 460",
    price: "90,000.00",
    color: "Green",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: 1052,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/JD_6110_D.png",
    productName: "JD 6110 D",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1053,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/joohn_deere-removebg-preview.png",
    productName: "6170",
    price: "75,000.00",
    color: "Green",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1054,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/jx_80-removebg-preview.png",
    productName: "jx 80",
    price: "70,000.00",
    color: "Green",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1055,
    img: "https://s3-us-west-2.amazonaws.com/ht-mobileassets/ti_massey_ferguson_tractor_mf7614.png",
    productName: "Massey Ferguson 7614",
    price: "90,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding tasks.",
  },
  {
    _id: 1056,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/6713-removebg-preview.png",
    productName: "6713",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1057,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/136_Preet_7549.png",
    productName: "Preet 7549 2WD",
    price: "75,000.00",
    color: "Red",
    badge: true,
    des: "Compact and efficient for small farms.",
  },
  {
    _id: 1058,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Mahindra_6005.png",
    productName: "Mahindra 6005",
    price: "70,000.00",
    color: "Red",
    badge: true,
    des: "High performance for demanding applications.",
  },
  {
    _id: 1059,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Massey_Ferguson_7618.png",
    productName: "Massey Ferguson 7618",
    price: "90,000.00",
    color: "Red",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1060,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/13_Sonalika_Di_750_III.png",
    productName: "Sonalika Di 750 III",
    price: "80,000.00",
    color: "Green",
    badge: true,
    des: "Ideal for heavy-duty tasks.",
  },
  {
    _id: 1061,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Isuzu_FRR.png",
    productName: "Isuzu FRR",
    price: "100,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
  {
    _id: 1062,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Kubota_L4508.png",
    productName: "Kubota L4508",
    price: "85,000.00",
    color: "Orange",
    badge: true,
    des: "Reliable and efficient for various tasks.",
  },
  {
    _id: 1063,
    img: "https://ht-mobileassets.s3.amazonaws.com/tractorModels/Isuzu_ELF_Tipper.png",
    productName: "Isuzu ELF Tipper",
    price: "90,000.00",
    color: "Blue",
    badge: true,
    des: "Versatile and durable for various tasks.",
  },
];
// =================== PaginationItems End here =================
